# Generated by Django 4.1.2 on 2023-04-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_list',
            name='log',
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log', models.JSONField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.game')),
                ('id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.list')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.patient')),
            ],
        ),
    ]
