# Generated by Django 4.1.2 on 2023-04-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0002_remove_game_list_log_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Patient', serialize=False, to='parkinsonUV_app.account'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Therapist', serialize=False, to='parkinsonUV_app.account'),
        ),
    ]
