# Generated by Django 4.1.2 on 2023-04-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0003_account_alter_patient_id_alter_therapist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
