# Generated by Django 4.1.2 on 2023-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0004_remove_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
