# Generated by Django 4.1.2 on 2023-05-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0006_alter_account_id_type_alter_patient_id_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='id',
            new_name='user_id',
        ),
    ]
