# Generated by Django 4.1.2 on 2023-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0008_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='document_id',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='document_type',
            field=models.CharField(default='C.C.', max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='user_picture',
            field=models.CharField(default='NN', max_length=400),
        ),
    ]
