# Generated by Django 4.2.2 on 2023-07-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_type', models.IntegerField()),
                ('document_id', models.IntegerField(default=0, max_length=50)),
                ('document_type', models.CharField(default='C.C.', max_length=40)),
                ('user_picture', models.CharField(default='NN', max_length=400)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='N/A', max_length=500)),
                ('game_picture', models.CharField(default='N/A', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Game_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.JSONField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('time_seconds', models.IntegerField()),
                ('specifications', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(through='parkinsonUV_app.Game_list', to='parkinsonUV_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Parkinson_phase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Patient', serialize=False, to='parkinsonUV_app.account')),
                ('id_type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('cell', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('id_parkinson_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.parkinson_phase')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Therapist', serialize=False, to='parkinsonUV_app.account')),
                ('id_type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('cell', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game_list',
            name='id_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.list'),
        ),
        migrations.AddField(
            model_name='game',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.game_type'),
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log', models.JSONField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.game')),
                ('id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.list')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='id_therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.therapist'),
        ),
        migrations.AddField(
            model_name='list',
            name='id_patient',
            field=models.ManyToManyField(null='true', to='parkinsonUV_app.patient'),
        ),
        migrations.AddField(
            model_name='list',
            name='id_therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.therapist'),
        ),
    ]
