# Generated by Django 4.2.2 on 2023-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0002_remove_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_list',
            name='setting',
            field=models.JSONField(null='true'),
        ),
    ]
