# Generated by Django 4.2.2 on 2023-08-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0003_alter_game_list_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('interval', models.IntegerField()),
                ('last_scheduled_date', models.CharField(max_length=25)),
                ('id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.list')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.patient')),
                ('id_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('log', models.CharField(max_length=1000)),
                ('id_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.activity')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.patient')),
                ('id_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.therapist')),
            ],
        ),
        migrations.DeleteModel(
            name='Registers',
        ),
    ]
