# Generated by Django 4.2.2 on 2023-08-16 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0004_activity_session_delete_registers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_scheduled_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='Realizado', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='document_id',
            field=models.IntegerField(default=0),
        ),
    ]
