# Generated by Django 4.1.2 on 2023-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='id_type',
            field=models.IntegerField(),
        ),
    ]
