# Generated by Django 4.2.2 on 2023-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0005_remove_activity_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_list',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
