# Generated by Django 4.2.2 on 2023-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0006_game_list_is_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='log',
        ),
    ]
