# Generated by Django 4.2.2 on 2023-10-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0007_remove_session_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.JSONField()),
                ('id_game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.game_list')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinsonUV_app.session')),
            ],
        ),
    ]
