# Generated by Django 4.2.2 on 2023-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0009_account_document_id_account_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_picture',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
