# Generated by Django 4.2.2 on 2023-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0010_game_game_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
