# Generated by Django 4.2.2 on 2023-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0010_alter_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id_patient',
        ),
        migrations.AddField(
            model_name='list',
            name='id_patient',
            field=models.ManyToManyField(to='parkinsonUV_app.patient'),
        ),
    ]
