# Generated by Django 4.2.2 on 2023-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinsonUV_app', '0011_remove_list_id_patient_list_id_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='games',
            field=models.ManyToManyField(through='parkinsonUV_app.Game_list', to='parkinsonUV_app.game'),
        ),
    ]
