# Generated by Django 4.0.5 on 2023-04-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('cell', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Games_settings',
            new_name='Game_settings',
        ),
        migrations.RenameModel(
            old_name='Games_type',
            new_name='Game_type',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('cell', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=3)),
                ('is_active', models.BooleanField()),
                ('id_parkinson_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.parkinson_phase')),
                ('id_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.patient')),
                ('id_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Game_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.JSONField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.game')),
                ('id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.list')),
                ('id_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.game_settings')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.game_type'),
        ),
    ]
